### ISSUE TITLE
SSL requests trigger InsecurePlatformWarning and SNIMissingWarning

### ISSUE THREAD

**Issue by bluezed** [Freso/script.module.requests#11] opened 2016-08-21 09:27 UTC
Hi,
sorry if this is actually not an issue with this module but I don't know where to turn instead so I hope you can help?
I'm using Kodi 16.1 on Win10 and have script.module.requests v2.9.1 as a dependency in one of my projects.
I'm doing POST requests against the JSON API at schedulesdirect.org which is on https and every time I do I get this message in my logs:

```
C:\Users\Kodi-Dev\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:315: 
SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication)
extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS
certificate, which can cause validation failures. 
For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
                                              SNIMissingWarning
11:17:46 T:8888   ERROR: C:\Users\Kodi-Dev\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:120: 
InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from
configuring SSL appropriately and may cause certain SSL connections to fail. 
For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
```

Since I can't just run a pip install as suggested in the links on a user's Kodi installation I'm wondering if there's any other way of getting rid of these errors? 

Any help would be much appreciated!

Many thanks! :+1:

**Comment by beenje** [comment] 2016-09-17 18:47
Hi,
Sorry for the late reply but I've been on vacation.

The problem is linked to Python older than 2.7.9.
On Windows, Python is packaged with Kodi. So there is not much to do but to wait for Kodi to update Python.

Looking at the source, in the master branch, https://github.com/xbmc/xbmc/blob/master/project/BuildDependencies/scripts/0_package.list, Python has been upgraded to: python-2.7.11-win32-vc140-v2.7z

So this problem will be fixed in next release of Kodi.
If you want more information about add-ons, the best is to ask in [Kodi forum](http://forum.kodi.tv/forumdisplay.php?fid=26).

**Closed as completed by beenje** 2016-09-17 18:47 UTC
